### ISSUE TITLE
[FEATURE]: Screebshots

### ISSUE THREAD

**Issue by nonetrix** [crystal-linux/getcryst.al#11]
### Is your feature request related to a problem? Please describe.

I don't know what to expect with this distro the text on the website is good, but besides what is there I still don't know what to expect like what themes does it use? 

### Describe the solution you'd like

Screenshots ideally of every desktop that can be used in their default state with a few windows open

### Describe alternatives you've considered

Video could be fine too I guess

### Additional context

![Screenshot at 2022-09-14 15-20-11](https://user-images.githubusercontent.com/45698918/190254374-8a84eb5b-84af-4196-b39b-f3dcdd2158c8.png)

**Comment by mrshmllow** [comment]
yes the overhaul is coming

**Comment by SomethingGeneric** [comment]
@mrshmllow want to leave this open until the big PR?
