### ISSUE TITLE
[BUG]: Small tweaks

### ISSUE THREAD

**Issue by not-my-segfault** [crystal-linux/getcryst.al#12]
### Describe the bug

Small things are a bit messy

- Distritbution instead of Distribution on the frontpage
- Probably best to remove all references to "Beginner friendly" as it's not our main focus anymore

### To reproduce the bug

1. Open site
2. Look

### Expected behavior

.

### Screenshots

![image](https://user-images.githubusercontent.com/30374463/190875587-8ba70757-50bd-4240-aa13-df77885275f0.png)

**Comment by mrshmllow** [comment]
technically i didnt make that spelling mistake :P
